# Generated by Django 5.1.1 on 2024-09-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WeatherData',
            new_name='SensorData',
        ),
    ]
