# Generated by Django 5.1.1 on 2024-09-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_weatherdata_sensordata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='pressure',
            field=models.FloatField(default=1013.25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='rain_detected',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
