# Generated by Django 5.1.1 on 2024-09-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_sensordata_pressure_sensordata_rain_detected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='pressure',
        ),
    ]
